name: chess
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  collection: ^1.17.1
  jovial_svg: ^1.1.15
  intl: ^0.19.0
  fl_chart: ^0.65.0
  provider: ^6.1.1
  google_fonts: ^6.2.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/activity.lichess-blitz.webp
    - assets/images/activity.lichess-bullet.webp
    - assets/images/activity.lichess-rapid.webp
    - assets/images/activity.puzzle-piece.webp
    - assets/images/logo_dark.png
